on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        java: [21, 24-ea]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: ${{matrix.java}}
        distribution: zulu
    - run: sbt "Jmh/run -i 10 -wi 10 -f1"
